version: "3.8"

services:
  front:
    build: "./front"
    image: "fido_front"
    networks:
      - fido_net
    ports:
      - "8080:8080"

  back:
    build: "./back"
    image: "fido_back"
    networks:
      - fido_net
    ports:
      - "5000:5000"

networks:
  fido_net:
